services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bytedeals-rabbitmq
    ports:
      - "5672:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    env_file: 
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  prometheus:
    image: prom/prometheus
    container_name: bytedeals-prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    env_file: 
      - .env

  grafana:
    image: grafana/grafana
    container_name: bytedeals-grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    env_file: 
      - .env
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: bytedeals-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: bytedeals-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  ollama:
    image: ollama/ollama
    container_name: bytedeals-ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
     - ollama_data:/root/.ollama
    restart: always

  ollama-init:
    image: curlimages/curl
    container_name: bytedeals-ollama-init
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
        echo 'Esperando Ollama...';
        
        until curl -s http://ollama:11434/api/tags;
        do
          sleep 2;
        done;

        echo 'Baixando modelo...';

        curl http://ollama:11434/api/pull -d '{
          \"name\": \"qwen2.5:1.5b\"
        }';

        echo 'Aquecendo modelo...';

        curl http://ollama:11434/api/generate -d '{
          \"model\": \"qwen2.5:1.5b\",
          \"prompt\": \"oi\",
          \"stream\": false
        }';

        echo 'Modelo pronto!';
      "

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bytedeals-bot
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - .env

  extractor:
    build:
      context: .
      dockerfile: extractor/Dockerfile
    container_name: bytedeals-extractor
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - .env

  publisher:
    build:
      context: .
      dockerfile: publisher/Dockerfile
    container_name: bytedeals-publisher
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - .env  

  agentia:
    build:
      context: .
      dockerfile: agentIA/Dockerfile
    container_name: bytedeals-agentia
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      ollama:
        condition: service_started
      ollama-init:
        condition: service_completed_successfully
    env_file: 
      - .env 

volumes:
  rabbitmq-data:
  prometheus-data:
  grafana-data:
  loki-data:
  ollama_data:

