{
 "title": "ByteDeals RabbitMQ",
 "panels": [
  {
   "title": "Mensagens Publicadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbit_messages_published_total"
    }
   ]
  },
  {
   "title": "Mensagens Consumidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rabbit_messages_consumed_total" }
   ]
  },
  {
   "title": "Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rabbit_messages_published_total - rabbit_messages_consumed_total"
    }
   ]
  }
 ]
}