global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "bot"
    static_configs:
      - targets:
          - "bot:8001"

  - job_name: "extractor"
    static_configs:
      - targets:
          - "extractor:8002"
